//by algolineu

customskybox
{
	qer_editorimage gfx/customsky/sky_ft
	surfaceparm noimpact
	surfaceparm nolightmap
	surfaceparm sky
       
	skyparms gfx/customsky/sky - -
}

// wf/wsw default
textures/blx_houses/ctf_sky { template customskybox }
textures/wdm4/sky4_s { template customskybox }
textures/blx_wtest3/sky { template customskybox }
textures/alley/oldsky { template customskybox }
textures/alley/newsky { template customskybox }
quake1/Sky_Template  { template customskybox }
quake2/Skybox_Template { template customskybox }
textures/blx/new_sky { template customskybox }
textures/baxandall/bax_sky { template customskybox }
textures/baxandall/bax_redsky { template customskybox }
textures/concretestrike/sky { template customskybox }
textures/concretestrike/sky_newlight { template customskybox }
textures/concretestrike/sky_surfacelight { template customskybox }
textures/wctf4/sky { template customskybox }
textures/wdm7/sky { template customskybox }
textures/starsky/starsky_light { template customskybox }
textures/starsky/starsky_nolight { template customskybox }
textures/wdm1/sky { template customskybox }
textures/melee/blacksky { template customskybox }
textures/wdm2/wdm2_sky { template customskybox }
textures/wdm9/sky_s { template customskybox }
textures/36_others/36sky2 { template customskybox }
textures/36_others/36sky3 { template customskybox }
textures/blx_ca/blx_ca_sky { template customskybox }
textures/blx_ca/blx_ca1_sky { template customskybox }
textures/reactors/sky_s { template customskybox }
textures/zone_neutre/skygrey { template customskybox }
textures/zone_neutre/skyblue { template customskybox }
textures/zone_neutre/skydarkblue { template customskybox }
textures/zone_neutre/znskybox { template customskybox }
textures/sky/pinksky { template customskybox }
textures/sky/violetsky { template customskybox }
textures/sky/purplesky { template customskybox }
textures/sky/indigosky { template customskybox }
textures/sky/orangesky { template customskybox }
textures/sky/miramar { template customskybox }
textures/sky/stormydays { template customskybox }
textures/shepas/sky_s { template customskybox }
textures/russus/russus_sky { template customskybox }
textures/wdm6/sky_s { template customskybox }
textures/deleo/sky { template customskybox }
textures/factory/blx_wt3_sky_orange_shader_reverse  { template customskybox }
textures/factory/blx_wt3_sky_orange_shader { template customskybox }

// downloads
textures/emtown/townsky { template customskybox }
textures/emtown/sky2 { template customskybox }
textures/skies/nec_city { template customskybox }
textures/acidwdm6/sky { template customskybox }
textures/acidwdm11/sky { template customskybox }
textures/wtest1/wtest1_sky { template customskybox }
textures/jerms_ca1/skybox { template customskybox }
textures/ae/orange { template customskybox }
textures/z/blx_wt3_sky_fixed { template customskybox }
textures/z/dot3sky { template customskybox }
textures/stormy_sky/stormydays { template customskybox }
textures/what_sky/sky { template customskybox }
textures/hipshot_m9_sky/space { template customskybox }
textures/spog/whitesky { template customskybox }
textures/spog/whitesky_dark { template customskybox }
textures/spog/whitesky_med { template customskybox }
textures/hipshot_m8/sky { template customskybox }
textures/hipshot_m15/sky { template customskybox }
textures/hipshot_m13/sky2 { template customskybox }
textures/msc/newsky { template customskybox }
textures/msc/clearsky { template customskybox }
textures/jerms_vast/skybox { template customskybox }
textures/sockter/skybox { template customskybox }
textures/jerms_ca3/skybox { template customskybox }
textures/lun_cpm18/lightsky { template customskybox }
textures/skies/ely_nevada { template customskybox }
textures/stormywhat_sky/stormywhat { template customskybox }
textures/dragee_gc3/drggc3_sky { template customskybox }
textures/Uptown/Sky { template customskybox }
textures/ctf/cas_killsky  { template customskybox }
textures/phdm5/sky  { template customskybox }
textures/toxic_sky/space  { template customskybox }
textures/wdm2/ink  { template customskybox }
textures/1626508557/sky-000  { template customskybox }
textures/1626508557/sky-001  { template customskybox }
textures/1626508557/sky-002  { template customskybox }
textures/1626508557/sky-003  { template customskybox }
textures/common/nightsky { template customskybox }
textures/common/nightsky2 { template customskybox }
textures/common/sky1 { template customskybox }
textures/common/sky_100 { template customskybox }
textures/common/sky_1000 { template customskybox }
textures/common/sky_150 { template customskybox }
textures/common/sky_30 { template customskybox }
textures/common/sky_300 { template customskybox }
textures/common/sky_500 { template customskybox }
textures/common/sky_u2 { template customskybox }
textures/skies/hellredclouds { template customskybox }
textures/skies/hellskybright { template customskybox }
textures/skies/hellskyteam { template customskybox }
textures/skies/kc_dm10sky { template customskybox }
textures/skies/kcbasesky_arena1_sky { template customskybox }
textures/skies/mkc_ctf5sky { template customskybox }
textures/skies/mkc_dm4sky { template customskybox }
textures/skies/mkc_sky { template customskybox }
textures/skies/nightsky_nocloud { template customskybox }
textures/skies/nightsky_nocloud_100 { template customskybox }
textures/skies/nightsky_nocloud_1000 { template customskybox }
textures/skies/nightsky_nocloud_200 { template customskybox }
textures/skies/nightsky_nocloud_400 { template customskybox }
textures/skies/nightsky_nocloud_500 { template customskybox }
textures/skies/nightsky_nocloud_600 { template customskybox }
textures/skies/nightsky_xian_dm15 { template customskybox }
textures/skies/nightsky_xian_dm2 { template customskybox }
textures/skies/nightsky_xian_dm3 { template customskybox }
textures/skies/nightsky_xian_dm4 { template customskybox }
textures/skies/pj_arena2sky { template customskybox }
textures/skies/pj_ctf1sky { template customskybox }
textures/skies/proto_sky { template customskybox }
textures/skies/space_holder { template customskybox }
textures/skies/stars_arena7 { template customskybox }
textures/skies/tim_dm14 { template customskybox }
textures/skies/toxicsky { template customskybox }
textures/skies/toxicskytim_ctf1 { template customskybox }
textures/skies/toxicskytim_dm3 { template customskybox }
textures/skies/toxicskytim_dm4 { template customskybox }
textures/skies/xblacksky { template customskybox }
textures/skies/xnightsky { template customskybox }
textures/skies/xnightsky_600 { template customskybox }
textures/skies/xtoxicsky_90_60 { template customskybox }
textures/skies/xtoxicsky_ctf { template customskybox }
textures/skies/xtoxicsky_dm14 { template customskybox }
textures/skies/xtoxicsky_dm3 { template customskybox }
textures/skies/xtoxicsky_dm4 { template customskybox }
textures/skies/xtoxicsky_q3ctf3 { template customskybox }
textures/skies/skybox { template customskybox }
textures/skies/xtoxicskytim_q3dm5 { template customskybox }
textures/skies/blacksky { template customskybox }
textures/skies/xblacksky_dm7 { template customskybox }
textures/skies/killsky { template customskybox }
textures/skies/tim_km2 { template customskybox }
textures/skies/tim_hell { template customskybox }
textures/skies/tim_dm3_red { template customskybox }
textures/skies/tim_dm14 { template customskybox }
textures/skies/tim_dm14red { template customskybox }
textures/skies/hellsky { template customskybox }
textures/skies/xtoxicsky_dm3 { template customskybox }
textures/skies/xtoxicsky_dm9 { template customskybox }
textures/skies/xtoxicsky_ctf { template customskybox }
textures/skies/xtoxicsky_tourney { template customskybox }
textures/skies/nightsky_xian_dm1 { template customskybox }
textures/skies/proto_sky { template customskybox }
textures/skies/mkc_ctf5sky { template customskybox }
textures/skies/mkc_dm4sky { template customskybox }
textures/castle/sky_castle1 { template customskybox }
textures/hell/hellsky2goo { template customskybox }
textures/skies/toxicskytim_dm7 { template customskybox }
textures/skies/q3dm0 { template customskybox }
textures/skies/toxicskytim_dm9 { template customskybox }
textures/skies/toxicskytim_dm8 { template customskybox }
textures/skies/toxicskytim_dm3 { template customskybox }
textures/skies/toxicskytim_blue { template customskybox }
textures/skies/toxicskytim_dm5 { template customskybox }
textures/skies/toxicskytim_dm2 { template customskybox }
// ♥
